apiVersion: v1
kind: Service
metadata:
  name: spring-grpc-client-lb
spec:
  type: LoadBalancer
  selector:
    app: spring-grpc-client-service
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
