apiVersion: v1
kind: Service
metadata:
  name: spring-grpc-server
spec:
  type: LoadBalancer
  selector:
    app: spring-grpc-server-service
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
